/** Public engine API. */
export * from "./types";
export { ingestBrief, briefSchema, dailyBudget, targetCpa } from "./brief";
export { analyzeBrief } from "./analysis";
export { buildStrategy } from "./strategy";
export { generateCreatives } from "./creative";
export { generateLandingPage } from "./landing";
export { publishCampaigns } from "./publish";
export { derive, simulatePeriod, mergeSnapshots } from "./monitoring";
export { optimize, isConverged, aggregate } from "./optimization";
export { buildReport } from "./reporting";
export { runGrowthLoop } from "./orchestrator";
export type { RunConfig, RunResult, LoopIteration } from "./orchestrator";
export { enhanceCreativesWithAi } from "./creative-ai";
export { resolveProvider, RuleBasedProvider, ClaudeProvider } from "../ai/provider";
export type { AiProvider, AiRequest, AiResponse } from "../ai/provider";
export { ROLE_SYSTEM_PROMPTS, ROLE_MODEL_HINT } from "../ai/roles";
export type { AiRole } from "../ai/roles";
export { getAdapter, listAdapters } from "./channels/registry";
export { thompsonAllocate, betaSample } from "./bandit";
export type { BanditArm, BanditAllocation, BanditOptions } from "./bandit";
export { CHANNEL_API_SPECS, getApiSpec } from "./channels/api-specs";
export type { ChannelApiSpec } from "./channels/api-specs";
export { MetaMarketingClient, MetaApiError, metaObjective, metaOptimizationGoal, metaCtaType } from "./channels/meta-client";
export { MetaAdsAdapter } from "./channels/meta";
export { GoogleAdsClient, GoogleAdsApiError, googleChannelType } from "./channels/google-client";
export { GoogleAdsAdapter } from "./channels/google";
export { TikTokAdsAdapter, tiktokObjective } from "./channels/tiktok";
export { LinkedInAdsAdapter } from "./channels/linkedin";
export type { ChannelAccount } from "./publish";
